import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
pd.options.display.float_format = '{:.6f}'.format
sns.set_theme(style="darkgrid")
sns.color_palette("rocket")
# Config plots

trueDecimation = 10;

# Import PPC data

dataTrue = pd.read_csv("cmake-build-debug/trueStatePPC.csv", sep=";")
dataError = pd.read_csv("cmake-build-debug/errorStatePPC.csv", sep=";")
dataState = pd.read_csv("cmake-build-debug/statePPC.csv", sep=";")
dataIMU = pd.read_csv("cmake-build-debug/IMUmeasPPC.csv", sep=";")
dataCAM = pd.read_csv("cmake-build-debug/CAMmeasPPC.csv", sep=";")
dataCov = pd.read_csv("cmake-build-debug/covariancePPC.csv",sep=';')

dataErrorDelay = pd.read_csv("cmake-build-debug/errorStateDelayPPC.csv", sep=";")
dataStateDelay = pd.read_csv("cmake-build-debug/stateDelayPPC.csv", sep=";")
dataCAMDelay = pd.read_csv("cmake-build-debug/CAMmeasDelayPPC.csv", sep=";")
dataCovDelay = pd.read_csv("cmake-build-debug/covarianceDelayPPC.csv",sep=';')

# Plot EKF Comparatives
# Plot positions

plt.figure()
plt.subplot(3,1,1)
plt.title("Position x Time")
plt.step(dataCAM['t'],dataCAM['p1'],linestyle=':',label="Meas. Delayed",where='post')
plt.step(dataCAMDelay['t'],dataCAMDelay['p1'],linestyle=':',label="Meas.",where='post')
plt.scatter(dataState['t'],dataState['p1'],label='State')
plt.scatter(dataStateDelay['t'],dataStateDelay['p1'],label='Update and re-propagation')
plt.plot(dataTrue['t'][::trueDecimation],dataTrue['p1'][::trueDecimation],linestyle='--',label='True')
#plt.fill_between(dataCov['t'], dataState['p1'] - np.sqrt(dataCov['P0']), dataState['p1'] + np.sqrt(dataCov['P0']), color='b', alpha=0.2, label="STD")
plt.legend()
plt.xlabel("Time [s]")
plt.ylabel(r"$p_x$")
#plt.grid()

plt.subplot(3,1,2)
plt.step(dataCAM['t'],dataCAM['p2'],linestyle=':',label="Meas. Delayed",where='post')
plt.step(dataCAMDelay['t'],dataCAMDelay['p2'],linestyle=':',label="Meas.",where='post')
plt.scatter(dataState['t'],dataState['p2'],label='State')
plt.scatter(dataStateDelay['t'],dataStateDelay['p2'],label='Update and re-propagation')
plt.plot(dataTrue['t'][::trueDecimation],dataTrue['p2'][::trueDecimation],linestyle='--',label='True')
#plt.fill_between(dataCov['t'], dataState['p2'] - np.sqrt(dataCov['P1']), dataState['p2'] + np.sqrt(dataCov['P1']), color='b', alpha=0.2, label="STD")
plt.legend()
plt.xlabel("Time [s]")
plt.ylabel(r"$p_y$")
#plt.grid()

plt.subplot(3,1,3)
plt.step(dataCAM['t'],dataCAM['p3'],linestyle=':',label="Meas. Delayed",where='post')
plt.step(dataCAMDelay['t'],dataCAMDelay['p3'],linestyle=':',label="Meas.",where='post')
plt.scatter(dataState['t'],dataState['p3'],label='State')
plt.scatter(dataStateDelay['t'],dataStateDelay['p3'],label='Update and re-propagation')
plt.plot(dataTrue['t'][::trueDecimation],dataTrue['p3'][::trueDecimation],linestyle='--',label='True')
#plt.fill_between(dataCov['t'], dataState['p3'] - np.sqrt(dataCov['P2']), dataState['p3'] + np.sqrt(dataCov['P2']), color='b', alpha=0.2, label="STD")
plt.legend()
plt.xlabel("Time [s]")
plt.ylabel(r"$p_z$")
#plt.grid()
plt.show(block=False)

# Primeiro subplot sem 'sharex'
plt.figure()
ax = plt.subplot(3, 1, 1)
ax.scatter(dataCov['t'], dataCov.iloc[:, 1])
ax.scatter(dataCovDelay['t'], dataCovDelay.iloc[:, 1])
ax.set_ylabel(f"$P_{{{1,1}}}$", rotation=0,labelpad=15)
ax.set_title("Covariance Matrix Elements")

# Os demais subplots compartilhando o eixo x com o primeiro
for i in range(1, 3):
    ax = plt.subplot(3, 1, i+1, sharex=ax)
    ax.scatter(dataCov['t'], dataCov.iloc[:, i+1])
    ax.scatter(dataCovDelay['t'], dataCovDelay.iloc[:, i+1])
    ax.set_ylabel(f"$P_{{{i+1},{i+1}}}$", rotation=0,labelpad=15)

ax.set_xlabel("Time [s]")
plt.show(block=False)

# Primeiro subplot sem 'sharex'
plt.figure()
ax = plt.subplot(15, 1, 1)
ax.scatter(dataCov['t'], dataCov.iloc[:, 1])
ax.scatter(dataCovDelay['t'], dataCovDelay.iloc[:, 1])
ax.set_ylabel(f"$P_{{{1,1}}}$", rotation=0,labelpad=15)
ax.set_title("Covariance Matrix Elements")


# Os demais subplots compartilhando o eixo x com o primeiro
for i in range(1, 15):
    ax = plt.subplot(15, 1, i+1, sharex=ax)
    ax.scatter(dataCov['t'], dataCov.iloc[:, i+1])
    ax.scatter(dataCovDelay['t'], dataCovDelay.iloc[:, i+1])
    ax.set_ylabel(f"$P_{{{i+1},{i+1}}}$", rotation=0,labelpad=15)

ax.set_xlabel("Time [s]")
plt.show(block=False)

"""
plt.figure()
plt.subplot(3,1,1)
plt.title("Position x Time")
plt.step(dataState['t'],dataState['p1'],label='State')
plt.plot(dataTrue['t'][::trueDecimation],dataTrue['p1'][::trueDecimation],linestyle='--',label='True')
plt.fill_between(dataCov['t'], dataState['p1'] - np.sqrt(dataCov['P0']), dataState['p1'] + np.sqrt(dataCov['P0']), color='b', alpha=0.2, label="STD")
plt.legend()
plt.xlabel("Time [s]")
plt.ylabel(r"$p_x$")
#plt.grid()

plt.subplot(3,1,2)
plt.step(dataState['t'],dataState['p2'],label='State')
plt.plot(dataTrue['t'][::trueDecimation],dataTrue['p2'][::trueDecimation],linestyle='--',label='True')
plt.fill_between(dataCov['t'], dataState['p2'] - np.sqrt(dataCov['P1']), dataState['p2'] + np.sqrt(dataCov['P1']), color='b', alpha=0.2, label="STD")
plt.legend()
plt.xlabel("Time [s]")
plt.ylabel(r"$p_y$")
#plt.grid()

plt.subplot(3,1,3)
plt.step(dataState['t'],dataState['p3'],label='State')
plt.plot(dataTrue['t'][::trueDecimation],dataTrue['p3'][::trueDecimation],linestyle='--',label='True')
plt.fill_between(dataCov['t'], dataState['p3'] - np.sqrt(dataCov['P2']), dataState['p3'] + np.sqrt(dataCov['P2']), color='b', alpha=0.2, label="STD")
plt.legend()
plt.xlabel("Time [s]")
plt.ylabel(r"$p_z$")
#plt.grid()
plt.show(block=False)

# Plot Trajectory
fig = plt.figure()
vehicleX = np.array([1,0,0])
vehicleY = np.array([0,1,0])
vehicleZ = np.array([0,0,1])
ax = fig.add_subplot(111, projection='3d')
ax.plot(dataState['p1'],dataState['p2'],dataState['p3'],label='State')
ax.plot(dataTrue['p1'][::trueDecimation],dataTrue['p2'][::trueDecimation],dataTrue['p3'][::trueDecimation],linestyle='--',label='True')
ax.set_xlabel(r"$p_x$")
ax.set_ylabel(r"$p_y$")
ax.set_zlabel(r"$p_z$")
axis_limitX =[min(dataState['p1']-200),max(dataState['p1']+200)]
axis_limitY =[min(dataState['p2']-100),max(dataState['p2']+100)]
axis_limitZ =[min(dataState['p3']-100),max(dataState['p3']+100)]
ax.set_xlim(axis_limitX)
ax.set_ylim(axis_limitY)
ax.set_zlim(axis_limitZ)
plt.legend()
plt.title("Trajetory")

#Plot Velocity
plt.figure()
plt.subplot(3,1,1)
plt.title("Linear Velocity [m/s] x Time")
plt.plot(dataState['t'],dataState['v1'],label='State')
plt.plot(dataTrue['t'][::trueDecimation],dataTrue['v1'][::trueDecimation],linestyle='--',label='True')
plt.fill_between(dataCov['t'], dataState['v1'] - np.sqrt(dataCov['P3']), dataState['v1'] + np.sqrt(dataCov['P3']), color='b', alpha=0.2, label="STD")
plt.legend()
plt.xlabel("Time [s]")
plt.ylabel(r"$v_x$")
#plt.grid()

plt.subplot(3,1,2)
plt.plot(dataState['t'],dataState['v2'],label='State')
plt.plot(dataTrue['t'][::trueDecimation],dataTrue['v2'][::trueDecimation],linestyle='--',label='True')
plt.fill_between(dataCov['t'], dataState['v2'] - np.sqrt(dataCov['P4']), dataState['v2'] + np.sqrt(dataCov['P4']), color='b', alpha=0.2, label="STD")
plt.legend()
plt.xlabel("Time [s]")
plt.ylabel(r"$v_y$")
#plt.grid()

plt.subplot(3,1,3)
plt.plot(dataState['t'],dataState['v3'],label='State')
plt.plot(dataTrue['t'][::trueDecimation],dataTrue['v3'][::trueDecimation],linestyle='--',label='True')
plt.fill_between(dataCov['t'], dataState['v3'] - np.sqrt(dataCov['P5']), dataState['v3'] + np.sqrt(dataCov['P5']), color='b', alpha=0.2, label="STD")
plt.legend()
plt.xlabel("Time [s]")
plt.ylabel(r"$v_z$")
#plt.grid()
plt.show(block=False)

# Plot Orientation
plt.figure()
plt.subplot(4,1,1)
plt.title("CAM quaternion x Time")
plt.plot(dataCAM['t'],dataCAM['q1'],linestyle=':',label="Meas")
plt.plot(dataState['t'],dataState['q1'],label='State')
plt.plot(dataTrue['t'][::trueDecimation],dataTrue['q1'][::trueDecimation],linestyle='--',label='True')
#plt.fill_between(dataCov['t'], dataState['q1'] - np.sqrt(dataCov['P6']), dataState['q1'] + np.sqrt(dataCov['P6']), color='b', alpha=0.2, label="STD")
plt.legend()
plt.xlabel("Time [s]")
plt.ylabel(r"$q_\omega$")
#plt.grid()

plt.subplot(4,1,2)
plt.plot(dataCAM['t'],dataCAM['q2'],linestyle=':',label="Meas")
plt.plot(dataState['t'],dataState['q2'],label='State')
plt.plot(dataTrue['t'][::trueDecimation],dataTrue['q2'][::trueDecimation],linestyle='--',label='True')
#plt.fill_between(dataCov['t'], dataState['q2'] - np.sqrt(dataCov['P7']), dataState['q2'] + np.sqrt(dataCov['P7']), color='b', alpha=0.2, label="STD")
plt.legend()
plt.xlabel("Time [s]")
plt.ylabel(r"$q_x$")
#plt.grid()

plt.subplot(4,1,3)
plt.plot(dataCAM['t'],dataCAM['q3'],linestyle=':',label="Meas")
plt.plot(dataState['t'],dataState['q3'],label='State')
plt.plot(dataTrue['t'][::trueDecimation],dataTrue['q3'][::trueDecimation],linestyle='--',label='True')
#plt.fill_between(dataCov['t'], dataState['q3'] - np.sqrt(dataCov['P8']), dataState['q3'] + np.sqrt(dataCov['P8']), color='b', alpha=0.2, label="STD")
plt.legend()
plt.xlabel("Time [s]")
plt.ylabel(r"$q_y$")
#plt.grid()

plt.subplot(4,1,4)
plt.plot(dataCAM['t'],dataCAM['q4'],linestyle=':',label="Meas")
plt.plot(dataState['t'],dataState['q4'],label='State')
plt.plot(dataTrue['t'][::trueDecimation],dataTrue['q4'][::trueDecimation],linestyle='--',label='True')
#plt.fill_between(dataCov['t'], dataState['q4'] - np.sqrt(dataCov['P9']), dataState['q4'] + np.sqrt(dataCov['P9']), color='b', alpha=0.2, label="STD")
plt.xlabel("Time [s]")
plt.ylabel(r"$q_z$")
plt.legend()
#plt.grid()
plt.show(block=False)

# Plot Bias
plt.figure()
plt.subplot(3,1,1)
plt.title("Acceleration Bias [$m/s^2$] x Time")
plt.plot(dataState['t'],dataState['ab1'],label='State')
plt.plot(dataTrue['t'][::trueDecimation],dataTrue['ab1'][::trueDecimation],linestyle='--',label='True')
plt.fill_between(dataCov['t'], dataState['ab1'] - np.sqrt(dataCov['P9']), dataState['ab1'] + np.sqrt(dataCov['P9']), color='b', alpha=0.2, label="STD")
plt.legend()
plt.xlabel("Time [s]")
plt.ylabel(r"$a_{b,x}$")
#plt.grid()

plt.subplot(3,1,2)
plt.plot(dataState['t'],dataState['ab2'],label='State')
plt.plot(dataTrue['t'][::trueDecimation],dataTrue['ab2'][::trueDecimation],linestyle='--',label='True')
plt.fill_between(dataCov['t'], dataState['ab2'] - np.sqrt(dataCov['P10']), dataState['ab2'] + np.sqrt(dataCov['P10']), color='b', alpha=0.2, label="STD")
plt.legend()
plt.xlabel("Time [s]")
plt.ylabel(r"$a_{b,y}$")
#plt.grid()

plt.subplot(3,1,3)
plt.plot(dataState['t'],dataState['ab3'],label='State')
plt.plot(dataTrue['t'][::trueDecimation],dataTrue['ab3'][::trueDecimation],linestyle='--',label='True')
plt.fill_between(dataCov['t'], dataState['ab3'] - np.sqrt(dataCov['P11']), dataState['ab3'] + np.sqrt(dataCov['P11']), color='b', alpha=0.2, label="STD")
plt.legend()
plt.xlabel("Time [s]")
plt.ylabel(r"$a_{b,z}$")
#plt.grid()
plt.show(block=False)

plt.figure()
plt.subplot(3,1,1)
plt.title("Angular Velocity Bias [rad/s] x Time")
plt.plot(dataState['t'],dataState['wb1'],label='State')
plt.plot(dataTrue['t'][::trueDecimation],dataTrue['wb1'][::trueDecimation],linestyle='--',label='True')
plt.fill_between(dataCov['t'], dataState['wb1'] - np.sqrt(dataCov['P12']), dataState['wb1'] + np.sqrt(dataCov['P12']), color='b', alpha=0.2, label="STD")
plt.legend()
plt.xlabel("Time [s]")
plt.ylabel(r"$\omega_{b,x}$")
#plt.grid()

plt.subplot(3,1,2)
plt.plot(dataState['t'],dataState['wb2'],label='State')
plt.plot(dataTrue['t'][::trueDecimation],dataTrue['wb2'][::trueDecimation],linestyle='--',label='True')
plt.fill_between(dataCov['t'], dataState['wb2'] - np.sqrt(dataCov['P13']), dataState['wb2'] + np.sqrt(dataCov['P13']), color='b', alpha=0.2, label="STD")
plt.legend()
plt.xlabel("Time [s]")
plt.ylabel(r"$\omega_{b,y}$")
#plt.grid()

plt.subplot(3,1,3)
plt.plot(dataState['t'],dataState['wb3'],label='State')
plt.plot(dataTrue['t'][::trueDecimation],dataTrue['wb3'][::trueDecimation],linestyle='--',label='True')
plt.fill_between(dataCov['t'], dataState['wb3'] - np.sqrt(dataCov['P14']), dataState['wb3'] + np.sqrt(dataCov['P14']), color='b', alpha=0.2, label="STD")
plt.legend()
plt.xlabel("Time [s]")
plt.ylabel(r"$\omega_{b,z}$")
#plt.grid()
plt.show(block=False)

plt.figure()


# Plot Error States

plt.figure()
plt.subplot(3,1,1)
plt.title("Error State: Position [m] x Time")
plt.plot(dataError['t'],dataError['p1'])
plt.xlabel("Time [s]")
plt.ylabel(r"$\delta p_x$")
#plt.grid()

plt.subplot(3,1,2)
plt.plot(dataError['t'],dataError['p2'])
plt.xlabel("Time [s]")
plt.ylabel(r"$\delta p_y$")
#plt.grid()

plt.subplot(3,1,3)
plt.plot(dataError['t'],dataError['p3'])
plt.xlabel("Time [s]")
plt.ylabel(r"$\delta p_z$")
#plt.grid()
plt.show(block=False)

plt.figure()
plt.subplot(3,1,1)
plt.title("Error State: Linear Velocity [m/s] x Time")
plt.plot(dataError['t'],dataError['v1'])
plt.xlabel("Time [s]")
plt.ylabel(r"$\delta v_x$")
#plt.grid()

plt.subplot(3,1,2)
plt.plot(dataError['t'],dataError['v2'])
plt.xlabel("Time [s]")
plt.ylabel(r"$\delta v_y$")
#plt.grid()

plt.subplot(3,1,3)
plt.plot(dataError['t'],dataError['v3'])
plt.xlabel("Time [s]")
plt.ylabel(r"$\delta v_z$")
#plt.grid()
plt.show(block=False)

# Plot IMU measurements

plt.figure()
plt.subplot(3,1,1)
plt.title("IMU: Angular Velocity [rad/s] x Time")
plt.plot(dataIMU['t'],dataIMU['w1'])
plt.xlabel("Time [s]")
plt.ylabel(r"$\omega_{m,x}$")
#plt.grid()

plt.subplot(3,1,2)
plt.plot(dataIMU['t'],dataIMU['w2'])
plt.xlabel("Time [s]")
plt.ylabel(r"$\omega_{m,y}$")
#plt.grid()

plt.subplot(3,1,3)
plt.plot(dataIMU['t'],dataIMU['w3'])
plt.xlabel("Time [s]")
plt.ylabel(r"$\omega_{m,z}$")
#plt.grid()
plt.show(block=False)

plt.figure()
plt.subplot(3,1,1)
plt.title(r"IMU: Acceleration $[m/s^2]$ x Time")
plt.plot(dataIMU['t'],dataIMU['a1'])
plt.xlabel("Time [s]")
plt.ylabel(r"$a_{m,x}$")
#plt.grid()

plt.subplot(3,1,2)
plt.plot(dataIMU['t'],dataIMU['a2'])
plt.xlabel("Time [s]")
plt.ylabel(r"$a_{m,y}$")
#plt.grid()

plt.subplot(3,1,3)
plt.plot(dataIMU['t'],dataIMU['a3'])
plt.xlabel("Time [s]")
plt.ylabel(r"$a_{m,z}$")
#plt.grid()
plt.show(block=False)

# Plot CAM measurements

plt.figure()
plt.subplot(3,1,1)
plt.title("CAM: Position [m] x Time")
plt.plot(dataCAM['t'],dataCAM['p1'],label="Meas.")
plt.plot(dataTrue['t'][::trueDecimation],dataTrue['p1'][::trueDecimation],linestyle='--',label='True')
plt.legend()
plt.xlabel("Time [s]")
plt.ylabel(r"$p_x$")
#plt.grid()

plt.subplot(3,1,2)
plt.plot(dataCAM['t'],dataCAM['p2'],label="Meas.")
plt.plot(dataTrue['t'][::trueDecimation],dataTrue['p2'][::trueDecimation],linestyle='--',label='True')
plt.legend()
plt.xlabel("Time [s]")
plt.ylabel(r"$p_y$")
#plt.grid()

plt.subplot(3,1,3)
plt.plot(dataCAM['t'],dataCAM['p3'],label="Meas.")
plt.plot(dataTrue['t'][::trueDecimation],dataTrue['p3'][::trueDecimation],linestyle='--',label='True')
plt.legend()
plt.xlabel("Time [s]")
plt.ylabel(r"$p_z$")
#plt.grid()
plt.show(block=False)

plt.figure()
plt.subplot(4,1,1)
plt.title("CAM quaternion x Time")
plt.step(dataCAM['t'],dataCAM['q1'],label="Meas.")
plt.plot(dataTrue['t'][::trueDecimation],dataTrue['q1'][::trueDecimation],linestyle='--',label='True')
plt.xlabel("Time [s]")
plt.ylabel(r"$q_\omega$")
plt.legend()
#plt.grid()

plt.subplot(4,1,2)

plt.step(dataCAM['t'],dataCAM['q2'],label="Meas.")
plt.plot(dataTrue['t'][::trueDecimation],dataTrue['q2'][::trueDecimation],linestyle='--',label='True')
plt.xlabel("Time [s]")
plt.ylabel(r"$q_x$")
plt.legend()
#plt.grid()

plt.subplot(4,1,3)
plt.step(dataCAM['t'],dataCAM['q3'],label="Meas.")
plt.plot(dataTrue['t'][::trueDecimation],dataTrue['q3'][::trueDecimation],linestyle='--',label='True')
plt.xlabel("Time [s]")
plt.ylabel(r"$q_y$")
plt.legend()
#plt.grid()

plt.subplot(4,1,4)
plt.step(dataCAM['t'],dataCAM['q4'],label="Meas.")
plt.plot(dataTrue['t'][::trueDecimation],dataTrue['q4'][::trueDecimation],linestyle='--',label='True')
plt.xlabel("Time [s]")
plt.ylabel(r"$q_z$")
#plt.grid()
plt.legend()
plt.show(block=False)
"""
input("Pressione Enter para fechar os plots e encerrar...")
